export type { Hint, Budget, Reducer, Reduction, ReductionStats } from './types.js'
export { DEFAULT_BUDGET } from './types.js'
export { shrink, loadReducers, BUILTIN_REDUCERS, type ShrinkOptions } from './pipeline.js'
export { FileSpillStore, type SpillStore, type FileSpillStoreOptions } from './spill.js'
export { sizeReducer, reduceBySize, defaultKeep, type Keep } from './reducers/size.js'
export { testsReducer, reduceTestOutput, detectTestOutput } from './reducers/tests.js'
export { diffReducer, reduceDiff, detectDiff } from './reducers/diff.js'
export { jsonReducer, reduceJson, detectJson } from './reducers/json.js'
export { logReducer, reduceLog, detectLog } from './reducers/log.js'
export { treeReducer, reduceTree, detectTree } from './reducers/tree.js'
export { buildReducer, reduceBuild, detectBuild } from './reducers/build.js'
export { stacktraceReducer, reduceStacktrace, detectStacktrace } from './reducers/stacktrace.js'
export { repeatReducer, reduceRepeat, detectRepeat } from './reducers/repeat.js'
export { lintReducer, reduceLint, detectLint } from './reducers/lint.js'
export { installReducer, reduceInstall, detectInstall } from './reducers/install.js'
export { csvReducer, reduceCsv, detectCsv } from './reducers/csv.js'
export { gitlogReducer, reduceGitLog, detectGitLog } from './reducers/gitlog.js'
